// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vklgfjqjrjyliuwmeojg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrbGdmanFqcmp5bGl1d21lb2pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzMwMjcsImV4cCI6MjA2NTY0OTAyN30.9qanceyGi1NQqtyZmKxj4s1kXVyRLWqMZMuPFdV7mBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);